### ISSUE TITLE
All images missing

### ISSUE THREAD

**Issue by hoyalu** [Teifun2/nextcloud-cookbook-flutter#37]
Hi! I have no idea if the following is related with #21 and / or #22, since my Nextcloud resides on https://mydomain.tld/nc/. Which, from what I know, is perfectly valid.
While the web app works as expected, I can't see any images on Android. There's a short animation (small circles, bigger circles), and after that only empty space where the pictures should be. The category names are missing as well, but they might just be invisible in white on white. All other text is there, so by guessing or choosing the first entry (must be "all"), I can find every recipe. The recipes are missing their title picture as well.
I'm using version 0.3.5.

**Comment by ttcc-gh** [comment]
I can confirm the same problem on my S10 using the same URL style: [https://example.com/nc](url)

**Comment by Teifun2** [comment]
Hmm this is weird. 
Could one of you create a test account for me so i can check what exactly goes wrong?
You could send me the credentials over the matrix chat of nextcloud-cookbook or by mail to linard.schwendener@gmail.com

This would be the easiest way for me to debug this issue!

**Comment by ttcc-gh** [comment]
I created you an account. I joined the matrix chat as "Tom", just text me if any help is required.

**Comment by Teifun2** [comment]
Figured it out. Seems to be a problem with the url path /nc

I fixed it now and am currently building the release version that should fix this problem!

**Comment by renarena** [comment]
I just updated to 0.36 - still no images, url is .../foldername/ and i use LineageOS 17 + afwall

**Comment by Teifun2** [comment]
@renarena Hmm this is not what i had hoped ;(

Could you maybe also provide me with a test account to check what is going wrong?

**Comment by hoyalu** [comment]
Thank you! With 0.3.6, loading images ~works~ worked until I updated the Nextcloud app (→ #36). I can remember seeing all images, although some (or all? – no way to test it anymore) in low quality.

**Comment by katseassavvas** [comment]
Hi Teifun2, and thanks a lot for your work on this project. I didn't want to bog down the reviews on Google Play, so I searched around trying to find you. On my Android phone (Mi A3) the issue persists, but since the last update I also see this as the main screen when I open the app:

![image](https://user-images.githubusercontent.com/612178/104812698-b2f22e80-580c-11eb-9f00-0ca284f02c9d.png)

I can search for individual recipes, despite of the error, but they still don't show any images:

![image](https://user-images.githubusercontent.com/612178/104812718-c8ffef00-580c-11eb-9e58-d0994aa21d9a.png)

Information that may also be helpful:
- Some of my recipes aren't in English but in Greek.
- Could this mean that the app maybe having issues with folder/file naming?
- I'm running Nextcloud 20.0.5
- Cookbook version is 0.7.9

Let me know if there's anything I can do to help. Thanks again!

**Comment by Teifun2** [comment]
I created a new version which should fix this issue. It will take some hours before it will appear in the play store, alternatively you can directly install the apk which is attached on github under releases.

Can you please check and confirm if this solved your issues? @hoyalu @katseassavvas @renarena

**Comment by hoyalu** [comment]
Unfortunately, this is not the solution for my case. After starting the app, I get
(de) "Fehler beim laden (sic!) der Kategorien: Bad state: No element"
≈ (en) "Error while / with loading categories: Bad state: No element"
Perhaps the app can't deal with my not providing an image for every category / recipe?

**Comment by katseassavvas** [comment]
I see the same "No element" behavior @hoyalu is describing, but now the app loads the image for a recipe if I search it with a recipe name.

**Comment by renarena** [comment]
with nextcloud 19.01 it works now for me

**Comment by renarena** [comment]
it still works after updating to V20.5 after clearing cache

**Comment by Teifun2** [comment]
Can somone provide me a test account that shows this behaviour? (linard.schwendener@gmail.com)

**Comment by katseassavvas** [comment]
Yes, I'm willing. How should I go about doing that?

**Comment by Teifun2** [comment]
Just create a new account on your cloud with some. Test recipes that show the same behaviour with the app. Then send me login data to my email address. I will check the problem and you can delete the account after my analysis!

**Comment by katseassavvas** [comment]
Just sent the info. Thanks!

**Comment by pdugas** [comment]
Following...  Same issue with mobile app version 0.3.7, NC version 20.0.5, NC app version 0.7.10.

**Comment by Teifun2** [comment]
@katseassavvas With your account i can now see what the problem is! In earlier versions of the cookbook plugin i was able to get all un-categorized recipes with  index.php/apps/cookbook/category/*  In the newer version i need to get index.php/apps/cookbook/category/_ . I have to find out when this change happened to make sure it works also with the old version!

But its my bad that there is no "graceful" degradation!

**Comment by katseassavvas** [comment]
I'm glad you pinpointed the problem. Should I keep the account?

**Comment by Teifun2** [comment]
@katseassavvas it would be good if you could leave it until I have a working fix (so I can properly test it!) should be ready in 1-2 days I hope!

**Comment by katseassavvas** [comment]
@Teifun2 no pressure, I'm happy to help.

**Comment by Teifun2** [comment]
This should now be finally fixed! @hoyalu 

@katseassavvas Please let me know if everything works correctly! If so you can then delete the test account. (Much appreciated!)

**Comment by katseassavvas** [comment]
@Teifun2 it's working as intended, and it will be of great use to me. Thank you very much for the work you're doing! I'm deleting the account.

**Comment by hoyalu** [comment]
Version 0.3.8 + Nextcloud 20.0.5 + NC App 0.7.10 work like a charm for me. Thanks a lot! @Teifun2

I hope you all agree with my closing this issue as solved. @ttcc-gh ?
