### ISSUE TITLE
[Bug] Ingredient field looses focus after adding an ingredient

### ISSUE THREAD

**Issue by meichthys** [Teifun2/nextcloud-cookbook-flutter#98]
When creating a new recipe and adding an ingredient or tool, after adding the ingredient/tool, then clicking "+" to add another, the focus jumps to a different field (usually source - if not filled in).

**Comment by Teifun2** [comment]
I just checked an it is a little more complicated than i had hoped.

To really track which field was added "new" is a lot of code. 

I opted for the simpler variant to autofocus the list elements that have an empty string. Therefore after adding a new instruction/tool/ingredient it will jump to the first empty instruction/tool/ingredient.

Its not the best solution but should fix the most annoying jumps.

**Comment by meichthys** [comment]
Sounds good! I will try to recompile To test it out.👍

**Comment by Teifun2** [comment]
@meichthys Just as a heads up it is on the small-improvements branch :)

**Comment by Teifun2** [comment]
Delivered with 0.7.5

**Comment by meichthys** [comment]
I could be missing something or maybe am not using the right branch?
I'm still having a similar issue. Whenever i add a new ingredient or tool, the cursor jumps to `Total Time: Minutes` even if all the fields are filled:
![image](https://user-images.githubusercontent.com/10717998/150719120-6d335925-dcd6-40cd-912e-6e16e5d215c1.png)

**Comment by Teifun2** [comment]
@meichthys 
This is rather weird.
I included the change in the 0.7.5 Update. Which should be available soon on Google Play (waiting for approval)
or you can download the APK that is attached under the release tab.

If it is not working with these versions please notify me as this is currently working on my phone :(

**Comment by Teifun2** [comment]
@meichthys Ah makes sense.

Then it should be on master branch. It is possible that this auto-focus is not properly working on IOS :/
